[package]
name = "vpspec"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags="2.6.0"
sdl2= { version = "0.37.0", features = ["mixer"] }
serde={ version="1.0.219", features=["derive"] }
serde_json="1.0"